plugins:
  chat_read_receipts_enabled:
    default: true
    client: true
  chat_read_receipts_refresh_interval_seconds:
    default: 3
    type: integer
    min: 1
    client: true
  chat_read_receipts_inline_avatar_count:
    default: 5
    type: integer
    min: 1
    client: true
  chat_read_receipts_show_on_all_visible_messages:
    default: false
